DELETE http://localhost:3002/api/notifications/67e043ad87628fc62fa0632b/67e052fa69625f2201ce76ef
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMSIsImlkIjoiNjdlMDQzYWQ4NzYyOGZjNjJmYTA2MzJiIiwiaWF0IjoxNzQyNzU0Mzg5LCJleHAiOjE3NDI3NTc5ODl9.P5MMIdVOrBS-yp00bmR88GeAcy_1Z4WusGPLToKEslI
Content-Type: application/json

