DELETE http://localhost:3002/api/events/67b0718d8b1d23a77cabcaf3/attendees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphY2tkYW5pZWxzIiwiaWQiOiI2N2RhZmJlY2JhMzliN2UyMDI0YzJmMzEiLCJpYXQiOjE3NDI0OTE2NDYsImV4cCI6MTc0MjQ5NTI0Nn0.pM56imd4SY4gy4Ro0wmRJT9fpQq36ULSa2Ksy5kad6M
