### Find user by phone number
POST http://localhost:3002/api/auth/find-by-phone
Content-Type: application/json

{
  "phoneNumber": "98689602"
}

### Change Password
POST http://localhost:3002/api/auth/change-password
Content-Type: application/json

{
  "username": "anishG",
  "password": "Anish!!",
  "confirmPassword": "Anish!!",
  "otp": 1234
}

